### ISSUE TITLE
Auto python packages upgrade

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-data-indexer#17]
I've seen that weboob import wasn't working anymore a few days ago. I was about to submit an issue for "please update weboob-modules", but I saw you actually updated them in your personal repo weboob-modules. So I've manually done:

- log in as cozy (`sudo su cozy -p`)
- update requirements in the virtualenv (`. ./virtualenv/bin/activate && pip install -r requirements/common.txt -U`)
- update repo (`git pull`)

Two questions here:
- Are all these steps done automatically during an update? If not, that would be nice to do so.
- Could cozy-data-indexer be added to the list of system applications (i.e. next to Data-System / Home / Proxy / Controller in the "manage your apps" tab), for getting updates notifications and auto-updates?

**Comment by frankrousseau** [comment]
Hi @bnjbvr,

Thank you for mentioning. That would be a great idea. I ping @poupotte, @jsilvestre and @clochix . That way they are aware of the problem.

**Comment by nledez** [comment]
I think we can close this one too after weboob removal. WDYT @frankrousseau?

**Comment by bnjbvr** [comment]
As the original reporter of the issue, I think it's clearly fixed now, thanks for checking in @nledez!
